<a href="https://colab.research.google.com/github/anurag-chiplunkar/Citi-AIML/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

**Importing required libraries**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')

In [3]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [7]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
X[:, 2] = labelEncoder.fit_transform(X[:, 2])

In [9]:
# X[:, 2]

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_X_train = sc.fit_transform(X_train)
scaled_X_test = sc.fit_transform(X_test)

In [14]:
X_train

array([[0.0, 0.0, 1.0, ..., 0, 0, 143203.78],
       [0.0, 0.0, 1.0, ..., 1, 0, 8207.36],
       [1.0, 0.0, 0.0, ..., 1, 1, 101515.76],
       ...,
       [0.0, 1.0, 0.0, ..., 1, 1, 138051.19],
       [1.0, 0.0, 0.0, ..., 1, 1, 141822.8],
       [0.0, 0.0, 1.0, ..., 1, 1, 96658.26]], dtype=object)

In [15]:
scaled_X_train

array([[-1.01055571, -0.57504086,  1.74954671, ..., -1.55056613,
        -1.02199176,  0.74416401],
       [-1.01055571, -0.57504086,  1.74954671, ...,  0.64492573,
        -1.02199176, -1.59596268],
       [ 0.98955455, -0.57504086, -0.57157662, ...,  0.64492573,
         0.97848147,  0.02151338],
       ...,
       [-1.01055571,  1.73900686, -0.57157662, ...,  0.64492573,
         0.97848147,  0.65484524],
       [ 0.98955455, -0.57504086, -0.57157662, ...,  0.64492573,
         0.97848147,  0.72022509],
       [-1.01055571, -0.57504086,  1.74954671, ...,  0.64492573,
         0.97848147, -0.06269008]])

# Building an ANN

In [16]:
ann = tf.keras.models.Sequential()

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
ann.fit(scaled_X_train, y_train, batch_size = 32, epochs = 100)

Making the predictions and evaluating the model

**Test Case**

Geography: France -- Encoded value is 1, 0, 0

Credit Score: 600

Gender: Male

Age: 40 yrs

Tenure: 3 yrs

Balance: 60000 Rs

Number of Products: 2

Does this customer have a credit card: Yes

Is this customer as Active Member: Yes

Estimated Salary: 50000 Rs

Will the customer leave the bank?

In [24]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 25ms/step
[[False]]
